package com.bhw.wechatsell.entity;

import com.bhw.wechatsell.enums.OrderStatusEnum;
import com.bhw.wechatsell.enums.PayStatusEnum;
import lombok.Data;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

@Entity
@Data
@DynamicUpdate //自动更新时间
public class OrderMaster {
    /**
     *订单Id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_id
     *
     * @mbg.generated
     */
    @Id
    private String orderId;

    /**
     *买家名字
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_name
     *
     * @mbg.generated
     */
    private String buyerName;

    /**
     *买家电话
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_phone
     *
     * @mbg.generated
     */
    private String buyerPhone;

    /**
     *买家地址
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_address
     *
     * @mbg.generated
     */
    private String buyerAddress;

    /**
     *买家微信Openid
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_openid
     *
     * @mbg.generated
     */
    private String buyerOpenid;

    /**
     *订单总金额
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_amount
     *
     * @mbg.generated
     */
    private BigDecimal orderAmount;

    /**
     *订单状态，默认为0新下单
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_status
     *
     * @mbg.generated
     */
    private Byte orderStatus = OrderStatusEnum.NEW.getCode();

    /**
     *支付状态，默认为0未支付
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.pay_status
     *
     * @mbg.generated
     */
    private Byte payStatus = PayStatusEnum.WAIT.getCode();

    /**
     *创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *更新时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.order_id
//     *
//     * @return the value of order_master.order_id
//     *
//     * @mbg.generated
//     */
//    public String getOrderId() {
//        return orderId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.order_id
//     *
//     * @param orderId the value for order_master.order_id
//     *
//     * @mbg.generated
//     */
//    public void setOrderId(String orderId) {
//        this.orderId = orderId == null ? null : orderId.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.buyer_name
//     *
//     * @return the value of order_master.buyer_name
//     *
//     * @mbg.generated
//     */
//    public String getBuyerName() {
//        return buyerName;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.buyer_name
//     *
//     * @param buyerName the value for order_master.buyer_name
//     *
//     * @mbg.generated
//     */
//    public void setBuyerName(String buyerName) {
//        this.buyerName = buyerName == null ? null : buyerName.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.buyer_phone
//     *
//     * @return the value of order_master.buyer_phone
//     *
//     * @mbg.generated
//     */
//    public String getBuyerPhone() {
//        return buyerPhone;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.buyer_phone
//     *
//     * @param buyerPhone the value for order_master.buyer_phone
//     *
//     * @mbg.generated
//     */
//    public void setBuyerPhone(String buyerPhone) {
//        this.buyerPhone = buyerPhone == null ? null : buyerPhone.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.buyer_address
//     *
//     * @return the value of order_master.buyer_address
//     *
//     * @mbg.generated
//     */
//    public String getBuyerAddress() {
//        return buyerAddress;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.buyer_address
//     *
//     * @param buyerAddress the value for order_master.buyer_address
//     *
//     * @mbg.generated
//     */
//    public void setBuyerAddress(String buyerAddress) {
//        this.buyerAddress = buyerAddress == null ? null : buyerAddress.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.buyer_openid
//     *
//     * @return the value of order_master.buyer_openid
//     *
//     * @mbg.generated
//     */
//    public String getBuyerOpenid() {
//        return buyerOpenid;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.buyer_openid
//     *
//     * @param buyerOpenid the value for order_master.buyer_openid
//     *
//     * @mbg.generated
//     */
//    public void setBuyerOpenid(String buyerOpenid) {
//        this.buyerOpenid = buyerOpenid == null ? null : buyerOpenid.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.order_amount
//     *
//     * @return the value of order_master.order_amount
//     *
//     * @mbg.generated
//     */
//    public BigDecimal getOrderAmount() {
//        return orderAmount;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.order_amount
//     *
//     * @param orderAmount the value for order_master.order_amount
//     *
//     * @mbg.generated
//     */
//    public void setOrderAmount(BigDecimal orderAmount) {
//        this.orderAmount = orderAmount;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.order_status
//     *
//     * @return the value of order_master.order_status
//     *
//     * @mbg.generated
//     */
//    public Byte getOrderStatus() {
//        return orderStatus;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.order_status
//     *
//     * @param orderStatus the value for order_master.order_status
//     *
//     * @mbg.generated
//     */
//    public void setOrderStatus(Byte orderStatus) {
//        this.orderStatus = orderStatus;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.pay_status
//     *
//     * @return the value of order_master.pay_status
//     *
//     * @mbg.generated
//     */
//    public Byte getPayStatus() {
//        return payStatus;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.pay_status
//     *
//     * @param payStatus the value for order_master.pay_status
//     *
//     * @mbg.generated
//     */
//    public void setPayStatus(Byte payStatus) {
//        this.payStatus = payStatus;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.create_time
//     *
//     * @return the value of order_master.create_time
//     *
//     * @mbg.generated
//     */
//    public LocalDateTime getCreateTime() {
//        return createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.create_time
//     *
//     * @param createTime the value for order_master.create_time
//     *
//     * @mbg.generated
//     */
//    public void setCreateTime(LocalDateTime createTime) {
//        this.createTime = createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column order_master.update_time
//     *
//     * @return the value of order_master.update_time
//     *
//     * @mbg.generated
//     */
//    public LocalDateTime getUpdateTime() {
//        return updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column order_master.update_time
//     *
//     * @param updateTime the value for order_master.update_time
//     *
//     * @mbg.generated
//     */
//    public void setUpdateTime(LocalDateTime updateTime) {
//        this.updateTime = updateTime;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", buyerName=").append(buyerName);
        sb.append(", buyerPhone=").append(buyerPhone);
        sb.append(", buyerAddress=").append(buyerAddress);
        sb.append(", buyerOpenid=").append(buyerOpenid);
        sb.append(", orderAmount=").append(orderAmount);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderMaster other = (OrderMaster) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getBuyerName() == null ? other.getBuyerName() == null : this.getBuyerName().equals(other.getBuyerName()))
            && (this.getBuyerPhone() == null ? other.getBuyerPhone() == null : this.getBuyerPhone().equals(other.getBuyerPhone()))
            && (this.getBuyerAddress() == null ? other.getBuyerAddress() == null : this.getBuyerAddress().equals(other.getBuyerAddress()))
            && (this.getBuyerOpenid() == null ? other.getBuyerOpenid() == null : this.getBuyerOpenid().equals(other.getBuyerOpenid()))
            && (this.getOrderAmount() == null ? other.getOrderAmount() == null : this.getOrderAmount().equals(other.getOrderAmount()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getBuyerName() == null) ? 0 : getBuyerName().hashCode());
        result = prime * result + ((getBuyerPhone() == null) ? 0 : getBuyerPhone().hashCode());
        result = prime * result + ((getBuyerAddress() == null) ? 0 : getBuyerAddress().hashCode());
        result = prime * result + ((getBuyerOpenid() == null) ? 0 : getBuyerOpenid().hashCode());
        result = prime * result + ((getOrderAmount() == null) ? 0 : getOrderAmount().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table order_master
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        orderId("order_id", "orderId", "VARCHAR", false),
        buyerName("buyer_name", "buyerName", "VARCHAR", false),
        buyerPhone("buyer_phone", "buyerPhone", "VARCHAR", false),
        buyerAddress("buyer_address", "buyerAddress", "VARCHAR", false),
        buyerOpenid("buyer_openid", "buyerOpenid", "VARCHAR", false),
        orderAmount("order_amount", "orderAmount", "DECIMAL", false),
        orderStatus("order_status", "orderStatus", "TINYINT", false),
        payStatus("pay_status", "payStatus", "TINYINT", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_master
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}