package com.bhw.wechatsell.entity;

import lombok.Data;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

@Entity
@Data
public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.detail_id
     *
     * @mbg.generated
     */
    @Id
    private String detailId;

    /**
     *订单Id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *商品Id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *商品名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *单价
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_price
     *
     * @mbg.generated
     */
    private BigDecimal productPrice;

    /**
     *商品数量
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_quantity
     *
     * @mbg.generated
     */
    private Integer productQuantity;

    /**
     *商品小图
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_icon
     *
     * @mbg.generated
     */
    private String productIcon;

}