package com.bhw.wechatsell.entity;

import com.bhw.wechatsell.enums.ProductStatusEnum;
import com.bhw.wechatsell.util.EnumUtil;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

@Entity
@DynamicUpdate  //更新时间
@Data
public class ProductInfo implements Serializable {

    private static final long serialVersionUID = -5063011112966371937L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated
     */
    @Id
    private String productId;

    /**
     *名字
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     *单价
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_price
     *
     * @mbg.generated
     */
    private BigDecimal productPrice;

    /**
     *库存
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_stock
     *
     * @mbg.generated
     */
    private Integer productStock;

    /**
     *描述
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_description
     *
     * @mbg.generated
     */
    private String productDescription;

    /**
     *小图
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_icon
     *
     * @mbg.generated
     */
    private String productIcon;

    /**
     *状态，0正常1下架
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_status
     *
     * @mbg.generated
     */
    private Byte productStatus = ProductStatusEnum.UP.getCode();

    /**
     *类目编码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.category_type
     *
     * @mbg.generated
     */
    private Integer categoryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    @JsonIgnore
    public ProductStatusEnum getProductStatusEnum(){
        return EnumUtil.getByCode(productStatus,ProductStatusEnum.class);
    }

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.product_id
//     *
//     * @return the value of product_info.product_id
//     *
//     * @mbg.generated
//     */
//    public String getProductId() {
//        return productId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.product_id
//     *
//     * @param productId the value for product_info.product_id
//     *
//     * @mbg.generated
//     */
//    public void setProductId(String productId) {
//        this.productId = productId == null ? null : productId.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.product_name
//     *
//     * @return the value of product_info.product_name
//     *
//     * @mbg.generated
//     */
//    public String getProductName() {
//        return productName;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.product_name
//     *
//     * @param productName the value for product_info.product_name
//     *
//     * @mbg.generated
//     */
//    public void setProductName(String productName) {
//        this.productName = productName == null ? null : productName.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.product_price
//     *
//     * @return the value of product_info.product_price
//     *
//     * @mbg.generated
//     */
//    public BigDecimal getProductPrice() {
//        return productPrice;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.product_price
//     *
//     * @param productPrice the value for product_info.product_price
//     *
//     * @mbg.generated
//     */
//    public void setProductPrice(BigDecimal productPrice) {
//        this.productPrice = productPrice;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.product_stock
//     *
//     * @return the value of product_info.product_stock
//     *
//     * @mbg.generated
//     */
//    public Integer getProductStock() {
//        return productStock;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.product_stock
//     *
//     * @param productStock the value for product_info.product_stock
//     *
//     * @mbg.generated
//     */
//    public void setProductStock(Integer productStock) {
//        this.productStock = productStock;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.product_description
//     *
//     * @return the value of product_info.product_description
//     *
//     * @mbg.generated
//     */
//    public String getProductDescription() {
//        return productDescription;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.product_description
//     *
//     * @param productDescription the value for product_info.product_description
//     *
//     * @mbg.generated
//     */
//    public void setProductDescription(String productDescription) {
//        this.productDescription = productDescription == null ? null : productDescription.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.product_icon
//     *
//     * @return the value of product_info.product_icon
//     *
//     * @mbg.generated
//     */
//    public String getProductIcon() {
//        return productIcon;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.product_icon
//     *
//     * @param productIcon the value for product_info.product_icon
//     *
//     * @mbg.generated
//     */
//    public void setProductIcon(String productIcon) {
//        this.productIcon = productIcon == null ? null : productIcon.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.product_status
//     *
//     * @return the value of product_info.product_status
//     *
//     * @mbg.generated
//     */
//    public Byte getProductStatus() {
//        return productStatus;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.product_status
//     *
//     * @param productStatus the value for product_info.product_status
//     *
//     * @mbg.generated
//     */
//    public void setProductStatus(Byte productStatus) {
//        this.productStatus = productStatus;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.category_type
//     *
//     * @return the value of product_info.category_type
//     *
//     * @mbg.generated
//     */
//    public Integer getCategoryType() {
//        return categoryType;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.category_type
//     *
//     * @param categoryType the value for product_info.category_type
//     *
//     * @mbg.generated
//     */
//    public void setCategoryType(Integer categoryType) {
//        this.categoryType = categoryType;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.create_time
//     *
//     * @return the value of product_info.create_time
//     *
//     * @mbg.generated
//     */
//    public LocalDateTime getCreateTime() {
//        return createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.create_time
//     *
//     * @param createTime the value for product_info.create_time
//     *
//     * @mbg.generated
//     */
//    public void setCreateTime(LocalDateTime createTime) {
//        this.createTime = createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column product_info.update_time
//     *
//     * @return the value of product_info.update_time
//     *
//     * @mbg.generated
//     */
//    public LocalDateTime getUpdateTime() {
//        return updateTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column product_info.update_time
//     *
//     * @param updateTime the value for product_info.update_time
//     *
//     * @mbg.generated
//     */
//    public void setUpdateTime(LocalDateTime updateTime) {
//        this.updateTime = updateTime;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productStock=").append(productStock);
        sb.append(", productDescription=").append(productDescription);
        sb.append(", productIcon=").append(productIcon);
        sb.append(", productStatus=").append(productStatus);
        sb.append(", categoryType=").append(categoryType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductInfo other = (ProductInfo) that;
        return (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProductPrice() == null ? other.getProductPrice() == null : this.getProductPrice().equals(other.getProductPrice()))
            && (this.getProductStock() == null ? other.getProductStock() == null : this.getProductStock().equals(other.getProductStock()))
            && (this.getProductDescription() == null ? other.getProductDescription() == null : this.getProductDescription().equals(other.getProductDescription()))
            && (this.getProductIcon() == null ? other.getProductIcon() == null : this.getProductIcon().equals(other.getProductIcon()))
            && (this.getProductStatus() == null ? other.getProductStatus() == null : this.getProductStatus().equals(other.getProductStatus()))
            && (this.getCategoryType() == null ? other.getCategoryType() == null : this.getCategoryType().equals(other.getCategoryType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProductPrice() == null) ? 0 : getProductPrice().hashCode());
        result = prime * result + ((getProductStock() == null) ? 0 : getProductStock().hashCode());
        result = prime * result + ((getProductDescription() == null) ? 0 : getProductDescription().hashCode());
        result = prime * result + ((getProductIcon() == null) ? 0 : getProductIcon().hashCode());
        result = prime * result + ((getProductStatus() == null) ? 0 : getProductStatus().hashCode());
        result = prime * result + ((getCategoryType() == null) ? 0 : getCategoryType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table product_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        productId("product_id", "productId", "VARCHAR", false),
        productName("product_name", "productName", "VARCHAR", false),
        productPrice("product_price", "productPrice", "DECIMAL", false),
        productStock("product_stock", "productStock", "INTEGER", false),
        productDescription("product_description", "productDescription", "VARCHAR", false),
        productIcon("product_icon", "productIcon", "VARCHAR", false),
        productStatus("product_status", "productStatus", "TINYINT", false),
        categoryType("category_type", "categoryType", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}