package com.bhw.wechatsell.entity;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

@Data
@Entity
public class SellerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.id
     *
     * @mbg.generated
     */
    @Id
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.openid
     *
     * @mbg.generated
     */
    private String openid;


}