package com.bhw.wechatsell.repository;

import com.bhw.wechatsell.entity.OrderDetail;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.jpa.repository.JpaRepository;

public interface OrderDetailRepository extends JpaRepository<OrderDetail, String> {

    List<OrderDetail> findByOrderId(String orderId);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    long countByExample(OrderDetailExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int deleteByExample(OrderDetailExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int deleteByPrimaryKey(String detailId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int insert(OrderDetail record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int insertSelective(OrderDetail record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    OrderDetail selectOneByExample(OrderDetailExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    OrderDetail selectOneByExampleSelective(@Param("example") OrderDetailExample example, @Param("selective") OrderDetail.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    List<OrderDetail> selectByExampleSelective(@Param("example") OrderDetailExample example, @Param("selective") OrderDetail.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    List<OrderDetail> selectByExample(OrderDetailExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    OrderDetail selectByPrimaryKeySelective(@Param("detailId") String detailId, @Param("selective") OrderDetail.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    OrderDetail selectByPrimaryKey(String detailId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(OrderDetail record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_detail
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(OrderDetail record);
}