package com.bhw.wechatsell.repository;

import com.bhw.wechatsell.entity.OrderMaster;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;

public interface OrderMasterRepository extends JpaRepository<OrderMaster,String> {

    Page<OrderMaster> findByBuyerOpenid(String buyerOpenid, Pageable pageable);




//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    long countByExample(OrderMasterExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int deleteByExample(OrderMasterExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int deleteByPrimaryKey(String orderId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int insert(OrderMaster record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int insertSelective(OrderMaster record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    OrderMaster selectOneByExample(OrderMasterExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    OrderMaster selectOneByExampleSelective(@Param("example") OrderMasterExample example, @Param("selective") OrderMaster.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    List<OrderMaster> selectByExampleSelective(@Param("example") OrderMasterExample example, @Param("selective") OrderMaster.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    List<OrderMaster> selectByExample(OrderMasterExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    OrderMaster selectByPrimaryKeySelective(@Param("orderId") String orderId, @Param("selective") OrderMaster.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    OrderMaster selectByPrimaryKey(String orderId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int updateByExampleSelective(@Param("record") OrderMaster record, @Param("example") OrderMasterExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int updateByExample(@Param("record") OrderMaster record, @Param("example") OrderMasterExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(OrderMaster record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table order_master
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(OrderMaster record);
}