package com.bhw.wechatsell.repository;

import com.bhw.wechatsell.entity.ProductInfo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

public interface ProductInfoRepository extends JpaRepository<ProductInfo, String> {

    List<ProductInfo> findByProductStatus(Byte productStatus);


//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    long countByExample(ProductInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int deleteByExample(ProductInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int deleteByPrimaryKey(String productId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int insert(ProductInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int insertSelective(ProductInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    ProductInfo selectOneByExample(ProductInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    ProductInfo selectOneByExampleSelective(@Param("example") ProductInfoExample example, @Param("selective") ProductInfo.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    List<ProductInfo> selectByExampleSelective(@Param("example") ProductInfoExample example, @Param("selective") ProductInfo.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    List<ProductInfo> selectByExample(ProductInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    ProductInfo selectByPrimaryKeySelective(@Param("productId") String productId, @Param("selective") ProductInfo.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    ProductInfo selectByPrimaryKey(String productId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int updateByExampleSelective(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int updateByExample(@Param("record") ProductInfo record, @Param("example") ProductInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(ProductInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_info
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(ProductInfo record);
}