package com.bhw.wechatsell.repository;

import com.bhw.wechatsell.entity.ProductCategory;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface ProductCategoryRepository extends JpaRepository<ProductCategory,Integer> {

    List<ProductCategory> findByCategoryTypeIn(List<Integer> categoryTypeList);
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    long countByExample(ProductCategoryExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int deleteByExample(ProductCategoryExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int deleteByPrimaryKey(Integer categoryId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int insert(ProductCategory record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int insertSelective(ProductCategory record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    ProductCategory selectOneByExample(ProductCategoryExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    ProductCategory selectOneByExampleSelective(@Param("example") ProductCategoryExample example, @Param("selective") ProductCategory.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    List<ProductCategory> selectByExampleSelective(@Param("example") ProductCategoryExample example, @Param("selective") ProductCategory.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    List<ProductCategory> selectByExample(ProductCategoryExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    ProductCategory selectByPrimaryKeySelective(@Param("categoryId") Integer categoryId, @Param("selective") ProductCategory.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    ProductCategory selectByPrimaryKey(Integer categoryId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int updateByExampleSelective(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int updateByExample(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(ProductCategory record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table product_category
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(ProductCategory record);
}