package com.bhw.wechatsell.repository;

import com.bhw.wechatsell.entity.SellerInfo;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.jpa.repository.JpaRepository;

public interface SellerInfoRepository  extends JpaRepository<SellerInfo,String> {

    SellerInfo findByOpenid(String openid);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    long countByExample(SellerInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int deleteByExample(SellerInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int deleteByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int insert(SellerInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int insertSelective(SellerInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    SellerInfo selectOneByExample(SellerInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    SellerInfo selectOneByExampleSelective(@Param("example") SellerInfoExample example, @Param("selective") SellerInfo.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    List<SellerInfo> selectByExampleSelective(@Param("example") SellerInfoExample example, @Param("selective") SellerInfo.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    List<SellerInfo> selectByExample(SellerInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     * @project https://github.com/itfsw/mybatis-generator-plugin
//     */
//    SellerInfo selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") SellerInfo.Column ... selective);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    SellerInfo selectByPrimaryKey(String id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int updateByExampleSelective(@Param("record") SellerInfo record, @Param("example") SellerInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int updateByExample(@Param("record") SellerInfo record, @Param("example") SellerInfoExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKeySelective(SellerInfo record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table seller_info
//     *
//     * @mbg.generated
//     */
//    int updateByPrimaryKey(SellerInfo record);
}