package com.bhw.wechatsell.dto;

import com.bhw.wechatsell.entity.OrderDetail;
import com.bhw.wechatsell.enums.OrderStatusEnum;
import com.bhw.wechatsell.enums.PayStatusEnum;
import com.bhw.wechatsell.util.EnumUtil;
import com.bhw.wechatsell.util.serializer.Date2LongSerializer;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Data
//@JsonInclude(JsonInclude.Include.NON_NULL)
public class OrderDTO {
    /**
     *订单Id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *买家名字
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_name
     *
     * @mbg.generated
     */
    private String buyerName;

    /**
     *买家电话
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_phone
     *
     * @mbg.generated
     */
    private String buyerPhone;

    /**
     *买家地址
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_address
     *
     * @mbg.generated
     */
    private String buyerAddress;

    /**
     *买家微信Openid
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_openid
     *
     * @mbg.generated
     */
    private String buyerOpenid;

    /**
     *订单总金额
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_amount
     *
     * @mbg.generated
     */
    private BigDecimal orderAmount;

    /**
     *订单状态，默认为0新下单
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_status
     *
     * @mbg.generated
     */
    private Byte orderStatus ;

    /**
     *支付状态，默认为0未支付
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.pay_status
     *
     * @mbg.generated
     */
    private Byte payStatus ;

    /**
     *创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.create_time
     *
     * @mbg.generated
     */
    @JsonSerialize(using = Date2LongSerializer.class)
    private Date createTime;

    /**
     *更新时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.update_time
     *
     * @mbg.generated
     */
    @JsonSerialize(using = Date2LongSerializer.class)
    private Date updateTime;

    List<OrderDetail> orderDetailList;

    @JsonIgnore
    public OrderStatusEnum getOrderStatusEnum() {
        return EnumUtil.getByCode(orderStatus, OrderStatusEnum.class);
    }

    @JsonIgnore
    public PayStatusEnum getPayStatusEnum() {
        return EnumUtil.getByCode(payStatus, PayStatusEnum.class);
    }
}
